#!/bin/bash
# Simple script to view the product page

echo "🚀 LLM Platform - Product Page Viewer"
echo "======================================"
echo ""
echo "The product page has been created successfully!"
echo ""
echo "File location: ./product-page.html"
echo ""
echo "To view the product page, you can:"
echo ""
echo "1. Open the file directly in your browser:"
echo "   - Simply double-click on 'product-page.html'"
echo "   - Or open your browser and navigate to the file"
echo ""
echo "2. Serve it with Python HTTP server (recommended for best experience):"
echo "   python3 -m http.server 8080"
echo "   Then open: http://localhost:8080/product-page.html"
echo ""
echo "3. View in Replit:"
echo "   The file is available in your Replit workspace"
echo ""
echo "The product page includes:"
echo "✓ Thought leadership content on on-premise LLM deployment"
echo "✓ Security and compliance benefits analysis"
echo "✓ Architecture diagram showing system components"
echo "✓ Screenshots of the application interface"
echo "✓ Business benefits and use cases"
echo "✓ Industry-specific applications"
echo ""
echo "Note: The page is a standalone HTML file with embedded CSS and JavaScript."
echo "No additional dependencies are required to view it."